version: 2
updates:
    # Gradle (pickdate-api build)
    -   package-ecosystem: "gradle"
        directory: "/pickdate-api"
        schedule:
            interval: "weekly"
        open-pull-requests-limit: 10

    # Gradle (root build / included builds)
    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "weekly"
        open-pull-requests-limit: 10
