services:
  postgres:
    image: 'postgres:17.5-alpine'
    environment:
      - POSTGRES_DB=pickdate
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass

    ports:
      - '54321:5432'
    networks:
      - pickdate

networks:
  pickdate:
    driver: bridge
