spring:
  application:
    name: pickdate

  docker:
    compose:
      lifecycle-management: start_and_stop

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: false

  datasource:
    url: jdbc:postgresql://${PICKDATE_DATABASE_URL:localhost:5432/pickdate}
    username: ${PICKDATE_DATABASE_USER:root}
    password: ${PICKDATE_DATABASE_PASS:pass}
    name: pickdate
    hikari:
      maximum-pool-size: 20

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

logback:
  log:
    dir: /app/logs

springdoc:
  show-actuator: false

management:
  info:
    git:
      mode: full
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers

server:
  forward-headers-strategy: framework

pickdate:
  keys:
    master-key: ${PICKDATE_MASTER_KEY:none}
    remember-me-key: ${PICKDATE_REMEMBER_ME_KEY:none}
