spring:
  application:
    name: pickdate

  session:
    jdbc:
      initialize-schema: never

  modulith:
    runtime:
      verification-enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        show_sql: false

  datasource:
    url: jdbc:postgresql://${PICKDATE_DATABASE_URL:localhost:5432/pickdate}
    username: ${PICKDATE_DATABASE_USER:root}
    password: ${PICKDATE_DATABASE_PASS:pass}
    name: pickdate
    hikari:
      maximum-pool-size: 20

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  servlet:
    context-path: ${PICKDATE_CONTEXT_PATH:/pickdate}
