name: on merge with main branch
on:
    push:
        branches: [ "main" ]

jobs:
    build:

        runs-on: self-hosted
        permissions:
            contents: read
        env:
          INCLUDE_SLOW_TESTS: "true"

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 25
                uses: actions/setup-java@v4
                with:
                    java-version: '25'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
                with:
                    validate-wrappers: false

            - name: Build
              run: ./gradlew build -x test

            - name: Tests
              run: ./gradlew test --info --stacktrace

            -   name: Setup k3s config
                run: |
                    mkdir -p ~/.kube
                    echo "${{ secrets.K3S_CONFIG }}" > ~/.kube/config
                    chmod 600 ~/.kube/config

            -   name: K3s get pods
                run: |
                    kubectl get pods --all-namespaces
