name: on pull request
on:
    pull_request:
        branches: [ "main" ]

jobs:
    build:

        runs-on: self-hosted
        permissions:
            contents: read
        env:
          INCLUDE_SLOW_TESTS: "true"

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 25
                uses: actions/setup-java@v4
                with:
                    java-version: '25'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
                with:
                    validate-wrappers: false

            - name: Build
              run: ./gradlew build -x test

            - name: Tests
              run: ./gradlew test --info --stacktrace

    dependency-submission:
        if: ${{ github.event.pull_request.head.repo.fork == false }}

        runs-on: self-hosted
        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 25
                uses: actions/setup-java@v4
                with:
                    java-version: '25'
                    distribution: 'temurin'

            -   name: Make Gradle wrapper executable
                run: chmod +x ./gradlew

            -   name: Generate and submit dependency graph
                uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
                continue-on-error: true
